version: '3'

services:
  hitbox:
    build: .
    image: mattipaksula/hitbox
    #environment:
    # - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./:/app
    ports:
      - 8080:8080
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
